---
:verbose: false
:concurrency: 5
:pidfile: .tmp/pids/sidekiq.pid
:logfile: .log/sidekiq.log
:queues:
  - default

:schedule:
  validate_video_attachment_worker:
    cron: '0 * * * * *'   # Runs once per minute
    class: Videos::ValidateVideoAttachmentWorker